In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data_test = np.genfromtxt('test.csv', delimiter = ',')
data_test

array([[ 0.02354575,  0.05068012, -0.0374625 , ..., -0.03949338,
        -0.03075121, -0.01350402],
       [-0.07816532, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.01811827, -0.08391984],
       [-0.03094232,  0.05068012,  0.00133873, ...,  0.1081111 ,
         0.08379677,  0.00306441],
       ...,
       [ 0.0090156 , -0.04464164, -0.01267283, ...,  0.03430886,
         0.02337484, -0.0052198 ],
       [ 0.01991321, -0.04464164, -0.03422907, ...,  0.03283281,
         0.02472532,  0.06933812],
       [ 0.01628068,  0.05068012,  0.00996123, ..., -0.03949338,
         0.01703713,  0.00720652]])

In [ ]:
data_train = np.genfromtxt('train.csv', delimiter = ',')
data_train

array([[-4.91050164e-02, -4.46416365e-02,  1.60854917e-01, ...,
         2.80165065e-02,  1.13486232e-02,  3.46000000e+02],
       [-7.09002471e-02,  5.06801187e-02, -8.91974838e-02, ...,
        -1.29079423e-02, -5.49250874e-02,  1.04000000e+02],
       [ 1.75052192e-03, -4.46416365e-02, -7.08746786e-02, ...,
        -2.25121719e-02,  7.20651633e-03,  4.90000000e+01],
       ...,
       [ 2.35457526e-02, -4.46416365e-02,  7.03187031e-02, ...,
        -1.91970476e-02, -9.36191133e-03,  2.88000000e+02],
       [ 1.62806757e-02,  5.06801187e-02,  7.24743273e-02, ...,
        -2.36445576e-02,  6.10539062e-02,  1.31000000e+02],
       [-9.14709343e-03,  5.06801187e-02, -3.09956318e-02, ...,
         6.20931562e-03,  2.79170509e-02,  4.20000000e+01]])

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
x_train = data_train[:,:10]
y_train = data_train[:,10:]
x_test = data_test[:,:10]


In [ ]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)

(331, 10)
(331, 1)
(111, 10)


In [ ]:
import pandas as pd
df = pd.DataFrame(x_train)
df.describe()

0           1           2  ...           7           8           9
count  331.000000  331.000000  331.000000  ...  331.000000  331.000000  331.000000
mean    -0.000214   -0.000293    0.000053  ...   -0.001473   -0.001594    0.000099
std      0.047207    0.047618    0.048627  ...    0.046591    0.048088    0.047263
min     -0.107226   -0.044642   -0.090275  ...   -0.076395   -0.126097   -0.137767
25%     -0.034575   -0.044642   -0.035307  ...   -0.039493   -0.035817   -0.034215
50%      0.005383   -0.044642   -0.008362  ...   -0.002592   -0.005145   -0.001078
75%      0.038076    0.050680    0.030979  ...    0.034309    0.032124    0.027917
max      0.110727    0.050680    0.170555  ...    0.185234    0.133599    0.135612

[8 rows x 10 columns]

Training Algorithm

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [ ]:
reg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
y_pred = reg.predict(x_test)
pred = np.around(y_pred,5)
print(pred)

[[105.52975]
 [105.80392]
 [178.60857]
 [ 79.38288]
 [ 52.95869]
 [ 98.87264]
 [150.71755]
 [ 34.86515]
 [113.13536]
 [161.50184]
 [135.86156]
 [ 94.71592]
 [138.48094]
 [141.37442]
 [158.76863]
 [171.65289]
 [106.44836]
 [103.9266 ]
 [ 95.38694]
 [167.40118]
 [166.53426]
 [101.53465]
 [252.45036]
 [147.02259]
 [214.78907]
 [161.27557]
 [210.61315]
 [ 71.78092]
 [189.65032]
 [206.61343]
 [219.98643]
 [168.80193]
 [116.84846]
 [178.744  ]
 [ 77.03247]
 [ 59.54633]
 [111.56738]
 [156.95187]
 [154.59591]
 [198.94457]
 [115.53884]
 [153.46699]
 [ 84.9618 ]
 [113.70337]
 [142.14156]
 [147.3104 ]
 [ 82.78072]
 [ 77.89237]
 [128.99006]
 [261.58712]
 [213.31188]
 [243.98791]
 [167.68132]
 [183.69712]
 [166.85927]
 [202.1144 ]
 [220.39236]
 [172.40288]
 [176.60898]
 [109.04657]
 [276.3779 ]
 [ 90.99942]
 [289.37221]
 [119.56253]
 [ 75.45688]
 [180.78599]
 [146.62093]
 [156.42382]
 [ 41.07904]
 [247.90645]
 [207.99121]
 [ 90.09641]
 [222.2417 ]
 [189.86378]
 [182.26954]
 [164.39881]
 [190.27067]

In [ ]:
np.savetxt('predicted_data.csv', pred ,fmt = "%0.5f",delimiter=',')